name: frontmobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  slide_to_act: ^2.0.1
  flutter_riverpod: ^2.3.6
  dio: ^5.2.0+1
  freezed_annotation: ^2.2.0
  iconly: ^1.0.1
  intl: ^0.18.1
  animate_do: ^3.0.2
  auto_animated: ^3.1.0
  http: ^1.2.0
  provider: ^6.0.5
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.8
  flutter_verification_code: ^1.1.7
  flutter_bloc: ^8.0.0
  flutter_paginate: ^1.0.0
  json_annotation: ^4.0.1
  rxdart: ^0.27.7
  fl_chart: ^0.68.0
  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/options.json
    - assets/futures.json
    - assets/perpetuals.json
    - assets/NFT_4.png
    - assets/logo.png

